script_name="KBBI 5 Koreksi Otomatis"
script_description = "Melakukan perubahan pada ejaan yang sering salah ditulis [Based MaxFireHeart Script]"
script_author      = "Padang Perwira Yudha"
script_version     = "1.0.2"
script_namespace="yudha.KBBI"

local haveDepCtrl,DependencyControl,depRec=pcall(require,"l0.DependencyControl")
if haveDepCtrl then
    script_version="1.0.2"
    depRec=DependencyControl{feed="https://raw.githubusercontent.com/Pcpkomputer/.bulan/master/DependencyControl.json"}
end

function kbbi_seleksi(subs, sel)
    for x, i in ipairs(sel) do
        line=subs[i]
        text=line.text
	    text=text
		:gsub("sekedar","sekadar{*sekedar}")
		:gsub("terimakasih","terima kasih{*terimakasih}")
		:gsub("dimana","di mana{*dimana}")
		:gsub("terlanjur","telanjur{*terlanjur}")
		:gsub("terlantar","telantar{*terlantar}")
		:gsub("frustasi","frustrasi{*frustasi}")
		:gsub("bis","bus{*bis}")
		:gsub("coklat","cokelat{*cokelat}")
		:gsub("hembus","embus{*hembus}")
		:gsub("goa","gua{*goa}")
		:gsub("harafiah","harfiah{*harafiah}")
		:gsub("himbau","imbau{*himbau}")
		:gsub("jerigen","jeriken{*jerigen}")
		:gsub("kaos","kaus{*kaos}")
		:gsub("lembab","lembap{*lembab}")
		:gsub("centimeter","sentimeter{*centimeter}")
		:gsub("seksama","saksama{*seksama}")
		:gsub("terong","terung{*terong}")
		:gsub("hutang","utang{*hutang}")
		:gsub("jaman","zaman{*jaman}")
		:gsub("rejeki","rezeki{*rejeki}")
		:gsub("silahkan","silakan{*silahkan}")
		:gsub("karir","karier{*karir}")
		:gsub("himpit","impit{*himpit}")
		:gsub("karuan","keruan{*karuan}")
		:gsub("darimana","dari mana{*darimana}")
		:gsub("dari pada","daripada{*dari pada}")
		:gsub("kemana","ke mana{*kemana}")
		:gsub("kesana","ke sana{*kesana}")
		:gsub("nampak","tampak{*nampak}")
		:gsub("tauco","taoco{*tauco}")
		:gsub("nafas","napas{*nafas}")
		:gsub("personil","personel{*personil}")
		:gsub("resiko","risiko{*resiko}")
		:gsub("anugrah","anugerah{*anugrah}")
		:gsub("detil","detail{*detil}")
		:gsub("mempedulikan","memedulikan{*mempedulikan}")
		:gsub("memperhatikan","memerhatikan{*memperhatikan}")
		:gsub("mempengaruhi","memengaruhi{*mempengaruhi}")
		:gsub("mengkupas","mengupas{*mengkupas}")
		:gsub("mengkorupsi","mengorupsi{*mengkorupsi}")
		:gsub("mempesona","memesona{*mempesona}")
		:gsub("hapal","hafal{*hapal}")
		:gsub("ijin","izin{*ijin}")
		:gsub("sumringah","semringah{*sumringah}")
		:gsub("sistim","sistem{*sistim}")
		:gsub("hentak","entak{*hentak}")
		:gsub("brengsek","berengsek{*brengsek}")
		:gsub("hisap","isap{*hisap}")
		:gsub("handal","andal{*handal}")
		:gsub("ada pun","adapun{*ada pun}")
		:gsub("andai pun","andaipun{*andai pun}")
		:gsub("atau pun","ataupun{*atau pun}")
		:gsub("bagaimana pun","bagaimanapun{*bagaimana pun}")
		:gsub("kendati pun","kendatipun{*kendati pun}")
		:gsub("sungguh pun","sungguhpun{*sungguh pun}")
		:gsub("sungguh pun","sungguhpun{*sungguh pun}")
		:gsub("sekali pun","sekalipun{*sekali pun}")
		:gsub("kalau pun","kalaupun{*kalau pun}")
		:gsub("walau pun","walaupun{*walau pun}")
		:gsub("biar pun","biarpun{*biar pun}")
		:gsub("mau pun","maupun{*mau pun}")
		:gsub("meski pun","meskipun{*meski pun}")
		:gsub("abjat","abjad{*abjat}")
		:gsub("aktifitas","aktivitas{*aktifitas}")
		:gsub("antri","antre{*antri}")
		:gsub("apotik","apotek{*apotik}")
		:gsub("atlit","atlet{*atlit}")
		:gsub("cabe","cabai{*cabe}")
		:gsub("pondasi","fondasi{*pondasi}")
		:gsub("frekwensi","frekuensi{*frekwensi}")
		:gsub("gubug","gubuk{*gubug}")
		:gsub("hakekat","hakikat{*hakekat}")
		:gsub("indera","indra{*indera}")
		:gsub("isteri","istri{*isteri}")
		:gsub("jendral","jenderal{*jendral}")
		:gsub("komplit","komplet{*komplit}")
		:gsub("kwalitas","kualitas{*kwalitas}")
		:gsub("kwitansi","kuitansi{*kwitansi}")
		:gsub("lobang","lubang{*lobang}")
		:gsub("milyar","miliar{*milyar}")
		:gsub("nomer","nomor{*}")
		:gsub("faham","paham{*faham}")
		:gsub("fikir","pikir{*fikir}")
		:gsub("praktek","praktik{*praktek}")
		:gsub("tehnik","teknik{*tehnik}")
		:gsub("malpraktik","malapraktik{*malpraktik}")
		:gsub("malfungsi","malafungsi{*malfungsi}")
		:gsub("akte","akta{*akte}")
		:gsub("ketapel","katapel{*ketapel}")
		:gsub("senggama","sanggama{*senggama}")
		:gsub("semedi","semadi{*semedi}")
		:gsub("amandemen","amendemen{*amandemen}")
		:gsub("aritmatika","aritmetika{*aritmatika}")
		:gsub("metoda","metode{*metoda}")
		:gsub("materai","meterai{*materai}")
		:gsub("kalendar","kalender{*kalendar}")
		:gsub("kadaluwarsa","kedaluwarsa{*kadaluwarsa}")
		:gsub("katagori","kategori{*kategori}")
		:gsub("sekular","sekuler{*sekular}")
		:gsub("selular","seluler{*selular}")
		:gsub("sirkular","sirkuler{*sirkular}")
		:gsub("survey","survei{*survey}")
		:gsub("formil","formal{*formil}")
		:gsub("komersil","komersial{*komersil}")
		:gsub("orisinil","orisinal{*orisinil}")
		:gsub("afdol","afdal{*afdol}")
		:gsub("cidera","cedera{*cidera}")
		:gsub("cendikiawan","cendekiawan{*cendikiawan}")
		:gsub("cinderamata","cenderamata{*cinderamata}")
		:gsub("diskotik","diskotek{*diskotik}")
		:gsub("ekstrim","ekstrem{*ekstrim}")
		:gsub("pinalti","penalti{*pinalti}")
		:gsub("piranti","peranti{*piranti}")
		:gsub("teoritis","teoretis{*teoritis}")
		:gsub("cengkeh","cengkih{*cengkeh}")
		:gsub("desertasi","disertasi{*desertasi}")
		:gsub("kaedah","kaidah{*kaedah}")
		:gsub("kempes","kempis{*kempes}")
		:gsub("retsleting","ritsleting{*retsleting}")
		:gsub("amuba","ameba{*amuba}")
		:gsub("punggawa","penggawa{*punggawa}")
		:gsub("surban","serban{*surban}")
		:gsub("kantung","kantong{*kantung}")
		:gsub("pastur","pastor{*pastur}")
		:gsub("supir","sopir{*supir}")
		:gsub("mangkok","mangkuk{*mangkok}")
		:gsub("saos","saus{*saos}")
		:gsub("sop","sup{*sop}")
		:gsub("obrak-abrik","ubrak-abrik{*obrak-abrik}")
		:gsub("kwalitas","kualitas{*kwalitas}")
		:gsub("kwintal","kuintal{*kwintal}")
		:gsub("hirarki","hierarki{*hirarki}")
		:gsub("insyaf","insaf{*insyaf}")
		:gsub("aktifis","aktivis{*aktifis}")
		:gsub("jerembab","jerembap{*jerembab}")
		:gsub("sembab","sembap{*sembab}")
		:gsub("tekat","tekad{*tekat}")
		:gsub("nekad","nekat{*nekad}")
		:gsub("bejad","bejat{*bejad}")
		:gsub("jenius","genius{*jenius}")
		:gsub("obyek","objek{*obyek}")
		:gsub("subyek","subjek{*subyek}")
		:gsub("jamrud","zamrud{*jamrud}")
		:gsub("kripik","keripik{*kripik}")
		:gsub("krupuk","kerupuk{*krupuk}")
		:gsub("ksatria","kesatria{*ksatria}")
		:gsub("sumatra","sumatera{*sumatra}")
		:gsub("trampil","terampil{*trampil}")
		:gsub("samudera","samudra{*samudera}")
		:gsub("terompet","trompet{*terompet}")
		:gsub("nahkoda","nakhoda{*nahkoda}")
		:gsub("tahta","takhta{*tahta}")
		:gsub("tahayul","takhayul{*tahayul}")
		:gsub("kharisma","karisma{*kharisma}")
		:gsub("syaraf","saraf{*syaraf}")
		:gsub("do'a","doa{*do'a}")
		:gsub("jum'at","jumat{*jum'at}")
		:gsub("mu'jizat","mukjizat{*mu'jizat}")
		:gsub("analisa","analisis{*analisa}")
		:gsub("diagnosa","diagnosis{*diagnosa}")
		:gsub("hipotesa","hipotesis{*hipotesa}")
		:gsub("sintesa","sintesis{*sintesa}")
		:gsub("produktifitas","produktivitas{*produktifitas}")
		:gsub("kreatifitas","kreativitas{*kreatifitas}")
		:gsub("efektifitas","efektivitas{*efektifitas}")
		:gsub("sportifitas","sportivitas{*sportifitas}")
		:gsub("selebriti","selebritas{*selebriti}")
		:gsub("validiti","validitas{*validiti}")
		:gsub("didramatisir","didramatisasi{*didramatisir}")
		:gsub("dinetralisir","dinetralisasi{*dinetralisir}")
		:gsub("koordinir","koordinasi{*koordinir}")
		:gsub("terorganisir","terorganisasi{*terorganisir}")
		:gsub("terealisir","terealisasi{*terealisir}")
		:gsub("pungkir","mungkir{*pungkir}")
		:gsub("hantar","antar{*hantar}")
		:gsub("panutan","anutan{*panutan}")
		:gsub("greget","gereget{*greget}")
		:gsub("klenteng","kelenteng{*klenteng}")
		:gsub("skak","sekak{*skak}")
		:gsub("stir","setir{*stir}")
		:gsub("ceret","cerek{*ceret}")
		:gsub("gombrong","gombroh{*gombrong}")
		:gsub("carut-marut","karut-marut{*carut-marut}")
		:gsub("mahzab","mazhab{*mahzab}")
		:gsub("negoisasi","negosiasi{*negoisasi}")
		:gsub("rileks","relaks{*rileks}")
		:gsub("sensorik","sensoris{*sensorik}")
		:gsub("tauge","taoge{*tauge}")
		:gsub("tauladan","teladan{*tauladan}")
		:gsub("taubat","tobat{*taubat}")
		:gsub("rapih","rapi{*rapih}")
		:gsub("terpercik","tepercik{*terpercik}")
		:gsub("berterbangan","beterbangan{*berterbangan}")
		:gsub("terperdaya","teperdaya{*terpedaya}")
		:gsub("hadang","adang{*hadang}")
		:gsub("menghadang","mengadang{*menghadang}")
		:gsub("hujam","hunjam{*hujam}")
		:gsub("menghujam","menghunjam{*menghujam}")
		:gsub("rubah","ubah{*rubah}")
		:gsub("merubah","mengubah{*merubah}")
		:gsub("hulu balang","hulubalang{*hulu balang}")
		:gsub("mana kala","manakala{*mana kala}")
		:gsub("walikota","wali kota{*walikota}")
		:gsub("adzan","azan{*adzan}")
		:gsub("ustadz","ustaz{*ustadz}")
		:gsub("dzikir","zikir{*dzikir}")
		:gsub("shalat","salat{*shalat}")
		:gsub("dzuhur","zuhur{*dzuhur}")
		:gsub("maghrib","magrib{*maghrib}")
		:gsub("ramadhan","ramadan{*ramadhan}")
		:gsub("raka'at","rakaat{*raka'at}")
		:gsub("taqwa","takwa{*taqwa}")
		:gsub("muadzin","muazin{*muadzin}")

		-- Kapital

		:gsub("Sekedar","Sekadar{*sekedar}")
		:gsub("Terimakasih","Terima kasih{*terimakasih}")
		:gsub("Dimana","Di mana{*dimana}")
		:gsub("Terlanjur","Telanjur{*terlanjur}")
		:gsub("Terlantar","Telantar{*terlantar}")
		:gsub("Frustasi","Frustrasi{*frustasi}")
		:gsub("Bis","Bus{*bis}")
		:gsub("Coklat","Cokelat{*cokelat}")
		:gsub("Hembus","Embus{*hembus}")
		:gsub("Goa","Gua{*goa}")
		:gsub("Harafiah","Harfiah{*harafiah}")
		:gsub("Himbau","Imbau{*himbau}")
		:gsub("Jerigen","Jeriken{*jerigen}")
		:gsub("Kaos","Kaus{*kaos}")
		:gsub("Lembab","Lembap{*lembab}")
		:gsub("Centimeter","Sentimeter{*centimeter}")
		:gsub("Seksama","Saksama{*seksama}")
		:gsub("Terong","Terung{*terong}")
		:gsub("Hutang","Utang{*hutang}")
		:gsub("Jaman","Zaman{*jaman}")
		:gsub("Rejeki","Rezeki{*rejeki}")
		:gsub("Silahkan","Silakan{*silahkan}")
		:gsub("Karir","Karier{*karir}")
		:gsub("Himpit","Impit{*himpit}")
		:gsub("Karuan","Keruan{*karuan}")
		:gsub("Darimana","Dari mana{*darimana}")
		:gsub("Dari pada","Daripada{*dari pada}")
		:gsub("Kemana","Ke mana{*kemana}")
		:gsub("Kesana","Ke sana{*Kesana}")
		:gsub("Nampak","Tampak{*nampak}")
		:gsub("Tauco","Taoco{*tauco}")
		:gsub("Nafas","Napas{*nafas}")
		:gsub("Personil","Personel{*personil}")
		:gsub("Resiko","Risiko{*resiko}")
		:gsub("Anugrah","Anugerah{*anugrah}")
		:gsub("Detil","Detail{*detil}")
		:gsub("Mempedulikan","Memedulikan{*mempedulikan}")
		:gsub("Memperhatikan","Memerhatikan{*memperhatikan}")
		:gsub("Mempengaruhi","Memengaruhi{*mempengaruhi}")
		:gsub("Mengkupas","Mengupas{*mengkupas}")
		:gsub("Mengkorupsi","Mengorupsi{*mengkorupsi}")
		:gsub("Mempesona","Memesona{*mempesona}")
		:gsub("Hapal","Hafal{*hapal}")
		:gsub("Ijin","Izin{*ijin}")
		:gsub("Sumringah","Semringah{*sumringah}")
		:gsub("Sistim","Sistem{*sistim}")
		:gsub("Hentak","Entak{*hentak}")
		:gsub("Brengsek","Berengsek{*brengsek}")
		:gsub("Hisap","Isap{*hisap}")
		:gsub("Handal","Andal{*handal}")
		:gsub("Ada pun","Adapun{*ada pun}")
		:gsub("Andai pun","Andaipun{*andai pun}")
		:gsub("Atau pun","Ataupun{*atau pun}")
		:gsub("Bagaimana pun","Bagaimanapun{*bagaimana pun}")
		:gsub("Kendati pun","Kendatipun{*kendati pun}")
		:gsub("Sungguh pun","Sungguhpun{*sungguh pun}")
		:gsub("Sungguh pun","Sungguhpun{*sungguh pun}")
		:gsub("Sekali pun","Sekalipun{*sekali pun}")
		:gsub("Kalau pun","Kalaupun{*kalau pun}")
		:gsub("Walau pun","Walaupun{*walau pun}")
		:gsub("Biar pun","Biarpun{*biar pun}")
		:gsub("Mau pun","Maupun{*mau pun}")
		:gsub("Meski pun","Meskipun{*meski pun}")
		:gsub("Abjat","Abjad{*abjat}")
		:gsub("Aktifitas","Aktivitas{*aktifitas}")
		:gsub("Antri","Antre{*antri}")
		:gsub("Apotik","Apotek{*apotik}")
		:gsub("Atlit","Atlet{*atlit}")
		:gsub("Cabe","Cabai{*cabe}")
		:gsub("Pondasi","Fondasi{*pondasi}")
		:gsub("Frekwensi","Frekuensi{*frekwensi}")
		:gsub("Gubug","Gubuk{*gubug}")
		:gsub("Hakekat","Hakikat{*hakekat}")
		:gsub("Indera","Indra{*indera}")
		:gsub("Isteri","Istri{*isteri}")
		:gsub("Jendral","Jenderal{*jendral}")
		:gsub("Komplit","Komplet{*komplit}")
		:gsub("Kwalitas","Kualitas{*kwalitas}")
		:gsub("Kwitansi","Kuitansi{*kwitansi}")
		:gsub("Lobang","Lubang{*lobang}")
		:gsub("Milyar","Miliar{*milyar}")
		:gsub("Nomer","Nomor{*}")
		:gsub("Faham","Paham{*faham}")
		:gsub("Fikir","Pikir{*fikir}")
		:gsub("Praktek","Praktik{*praktek}")
		:gsub("Tehnik","Teknik{*tehnik}")
		:gsub("Malpraktik","Malapraktik{*malpraktik}")
		:gsub("Malfungsi","Malafungsi{*malfungsi}")
		:gsub("Akte","Akta{*akte}")
		:gsub("Ketapel","Katapel{*ketapel}")
		:gsub("Senggama","Sanggama{*senggama}")
		:gsub("Semedi","Semadi{*semedi}")
		:gsub("Amandemen","Amendemen{*amandemen}")
		:gsub("Aritmatika","Aritmetika{*aritmatika}")
		:gsub("Metoda","Metode{*metoda}")
		:gsub("Materai","Meterai{*materai}")
		:gsub("Kalendar","Kalender{*kalendar}")
		:gsub("Kadaluwarsa","Kedaluwarsa{*kadaluwarsa}")
		:gsub("Katagori","Kategori{*kategori}")
		:gsub("Sekular","Sekuler{*sekular}")
		:gsub("Selular","Seluler{*selular}")
		:gsub("Sirkular","Sirkuler{*sirkular}")
		:gsub("Survey","Survei{*survey}")
		:gsub("Formil","Formal{*formil}")
		:gsub("Komersil","Komersial{*komersil}")
		:gsub("Orisinil","Orisinal{*orisinil}")
		:gsub("Afdol","Afdal{*afdol}")
		:gsub("Cidera","Cedera{*cidera}")
		:gsub("Cendikiawan","Cendekiawan{*cendikiawan}")
		:gsub("Cinderamata","Cenderamata{*cinderamata}")
		:gsub("Diskotik","Diskotek{*diskotik}")
		:gsub("Ekstrim","Ekstrem{*ekstrim}")
		:gsub("Pinalti","Penalti{*pinalti}")
		:gsub("Piranti","Peranti{*piranti}")
		:gsub("Teoritis","Teoretis{*teoritis}")
		:gsub("Cengkeh","Cengkih{*cengkeh}")
		:gsub("Desertasi","Disertasi{*desertasi}")
		:gsub("Kaedah","Kaidah{*kaedah}")
		:gsub("Kempes","Kempis{*kempes}")
		:gsub("Retsleting","Ritsleting{*retsleting}")
		:gsub("Amuba","Ameba{*amuba}")
		:gsub("Punggawa","Penggawa{*punggawa}")
		:gsub("Surban","Serban{*surban}")
		:gsub("Kantung","Kantong{*kantung}")
		:gsub("Pastur","Pastor{*pastur}")
		:gsub("Supir","Sopir{*supir}")
		:gsub("Mangkok","Mangkuk{*mangkok}")
		:gsub("Saos","Saus{*saos}")
		:gsub("Sop","Sup{*sop}")
		:gsub("Obrak-abrik","Ubrak-abrik{*obrak-abrik}")
		:gsub("Kwalitas","Kualitas{*kwalitas}")
		:gsub("Kwintal","Kuintal{*kwintal}")
		:gsub("Hirarki","Hierarki{*hirarki}")
		:gsub("Insyaf","Insaf{*insyaf}")
		:gsub("Aktifis","Aktivis{*aktifis}")
		:gsub("Jerembab","Jerembap{*jerembab}")
		:gsub("Sembab","Sembap{*sembab}")
		:gsub("Tekat","Tekad{*tekat}")
		:gsub("Nekad","Nekat{*nekad}")
		:gsub("Bejad","Bejat{*bejad}")
		:gsub("Jenius","Genius{*jenius}")
		:gsub("Obyek","Objek{*obyek}")
		:gsub("Subyek","Subjek{*subyek}")
		:gsub("Jamrud","Zamrud{*jamrud}")
		:gsub("Kripik","Keripik{*kripik}")
		:gsub("Krupuk","Kerupuk{*krupuk}")
		:gsub("Ksatria","Kesatria{*ksatria}")
		:gsub("Sumatra","Sumatera{*sumatra}")
		:gsub("Trampil","Terampil{*trampil}")
		:gsub("Samudera","Samudra{*samudera}")
		:gsub("Terompet","Trompet{*terompet}")
		:gsub("Nahkoda","Nakhoda{*nahkoda}")
		:gsub("Tahta","Takhta{*tahta}")
		:gsub("Tahayul","Takhayul{*tahayul}")
		:gsub("Kharisma","Karisma{*kharisma}")
		:gsub("Syaraf","Saraf{*syaraf}")
		:gsub("Do'a","Doa{*do'a}")
		:gsub("Jum'at","Jumat{*jum'at}")
		:gsub("Mu'jizat","Mukjizat{*mu'jizat}")
		:gsub("Analisa","Analisis{*analisa}")
		:gsub("Diagnosa","Diagnosis{*diagnosa}")
		:gsub("Hipotesa","Hipotesis{*hipotesa}")
		:gsub("Sintesa","Sintesis{*sintesa}")
		:gsub("Produktifitas","Produktivitas{*produktifitas}")
		:gsub("Kreatifitas","Kreativitas{*kreatifitas}")
		:gsub("Efektifitas","Efektivitas{*efektifitas}")
		:gsub("Sportifitas","Sportivitas{*sportifitas}")
		:gsub("Selebriti","Selebritas{*selebriti}")
		:gsub("Validiti","Validitas{*validiti}")
		:gsub("Didramatisir","Didramatisasi{*didramatisir}")
		:gsub("Dinetralisir","Dinetralisasi{*dinetralisir}")
		:gsub("Koordinir","Koordinasi{*koordinir}")
		:gsub("Terorganisir","Terorganisasi{*terorganisir}")
		:gsub("Terealisir","Terealisasi{*terealisir}")
		:gsub("Pungkir","Mungkir{*pungkir}")
		:gsub("Hantar","Antar{*hantar}")
		:gsub("Panutan","Anutan{*panutan}")
		:gsub("Greget","Gereget{*greget}")
		:gsub("Klenteng","Kelenteng{*klenteng}")
		:gsub("Skak","Sekak{*skak}")
		:gsub("Stir","Setir{*stir}")
		:gsub("Ceret","Cerek{*ceret}")
		:gsub("Gombrong","Gombroh{*gombrong}")
		:gsub("Carut-marut","Karut-marut{*carut-marut}")
		:gsub("Mahzab","Mazhab{*mahzab}")
		:gsub("Negoisasi","Negosiasi{*negoisasi}")
		:gsub("Rileks","Relaks{*rileks}")
		:gsub("Sensorik","Sensoris{*sensorik}")
		:gsub("Tauge","Taoge{*tauge}")
		:gsub("Tauladan","Teladan{*tauladan}")
		:gsub("Taubat","Tobat{*taubat}")
		:gsub("Rapih","Rapi{*rapih}")
		:gsub("Terpercik","Tepercik{*terpercik}")
		:gsub("Berterbangan","Beterbangan{*berterbangan}")
		:gsub("Terperdaya","Teperdaya{*terpedaya}")
		:gsub("Hadang","Adang{*hadang}")
		:gsub("Menghadang","Mengadang{*menghadang}")
		:gsub("Hujam","Hunjam{*hujam}")
		:gsub("Menghujam","Menghunjam{*menghujam}")
		:gsub("Rubah","Ubah{*rubah}")
		:gsub("Merubah","Mengubah{*merubah}")
		:gsub("Hulu balang","Hulubalang{*hulu balang}")
		:gsub("Mana kala","Manakala{*mana kala}")
		:gsub("Walikota","Wali kota{*walikota}")
		:gsub("Adzan","Azan{*adzan}")
		:gsub("Ustadz","Ustaz{*ustadz}")
		:gsub("Dzikir","Zikir{*dzikir}")
		:gsub("Shalat","Salat{*shalat}")
		:gsub("Dzuhur","Zuhur{*dzuhur}")
		:gsub("Maghrib","Magrib{*maghrib}")
		:gsub("Ramadhan","Ramadan{*ramadhan}")
		:gsub("Raka'at","Rakaat{*raka'at}")
		:gsub("Taqwa","Takwa{*taqwa}")
		:gsub("Muadzin","Muazin{*muadzin}")
		--kebiasan si fadli bangsat
		:gsub(", kan?",", 'kan")
		--------------------------
		if text:match("{%*[^}]-}") then line.actor="Tolong lebih teliti lagi, Mas!" end

	line.text=text
        subs[i]=line
    end
    return sel
end

------------------------------------------------------------------

function kbbi(subs)
    for i=1,#subs do
        if subs[i].class=="dialogue" then
            line=subs[i]
            text=subs[i].text
	    text=text
		:gsub("sekedar","sekadar{*sekedar}")
		:gsub("terimakasih","terima kasih{*terimakasih}")
		:gsub("dimana","di mana{*dimana}")
		:gsub("terlanjur","telanjur{*terlanjur}")
		:gsub("terlantar","telantar{*terlantar}")
		:gsub("frustasi","frustrasi{*frustasi}")
		:gsub("bis","bus{*bis}")
		:gsub("coklat","cokelat{*cokelat}")
		:gsub("hembus","embus{*hembus}")
		:gsub("goa","gua{*goa}")
		:gsub("harafiah","harfiah{*harafiah}")
		:gsub("himbau","imbau{*himbau}")
		:gsub("jerigen","jeriken{*jerigen}")
		:gsub("kaos","kaus{*kaos}")
		:gsub("lembab","lembap{*lembab}")
		:gsub("centimeter","sentimeter{*centimeter}")
		:gsub("seksama","saksama{*seksama}")
		:gsub("terong","terung{*terong}")
		:gsub("hutang","utang{*hutang}")
		:gsub("jaman","zaman{*jaman}")
		:gsub("rejeki","rezeki{*rejeki}")
		:gsub("silahkan","silakan{*silahkan}")
		:gsub("karir","karier{*karir}")
		:gsub("himpit","impit{*himpit}")
		:gsub("karuan","keruan{*karuan}")
		:gsub("darimana","dari mana{*darimana}")
		:gsub("dari pada","daripada{*dari pada}")
		:gsub("kemana","ke mana{*kemana}")
		:gsub("kesana","ke sana{*}kesana")
		:gsub("nampak","tampak{*nampak}")
		:gsub("tauco","taoco{*tauco}")
		:gsub("nafas","napas{*nafas}")
		:gsub("personil","personel{*personil}")
		:gsub("resiko","risiko{*resiko}")
		:gsub("anugrah","anugerah{*anugrah}")
		:gsub("detil","detail{*detil}")
		:gsub("mempedulikan","memedulikan{*mempedulikan}")
		:gsub("memperhatikan","memerhatikan{*memperhatikan}")
		:gsub("mempengaruhi","memengaruhi{*mempengaruhi}")
		:gsub("mengkupas","mengupas{*mengkupas}")
		:gsub("mengkorupsi","mengorupsi{*mengkorupsi}")
		:gsub("mempesona","memesona{*mempesona}")
		:gsub("hapal","hafal{*hapal}")
		:gsub("ijin","izin{*ijin}")
		:gsub("sumringah","semringah{*sumringah}")
		:gsub("sistim","sistem{*sistim}")
		:gsub("hentak","entak{*hentak}")
		:gsub("brengsek","berengsek{*brengsek}")
		:gsub("hisap","isap{*hisap}")
		:gsub("handal","andal{*handal}")
		:gsub("ada pun","adapun{*ada pun}")
		:gsub("andai pun","andaipun{*andai pun}")
		:gsub("atau pun","ataupun{*atau pun}")
		:gsub("bagaimana pun","bagaimanapun{*bagaimana pun}")
		:gsub("kendati pun","kendatipun{*kendati pun}")
		:gsub("sungguh pun","sungguhpun{*sungguh pun}")
		:gsub("sungguh pun","sungguhpun{*sungguh pun}")
		:gsub("sekali pun","sekalipun{*sekali pun}")
		:gsub("kalau pun","kalaupun{*kalau pun}")
		:gsub("walau pun","walaupun{*walau pun}")
		:gsub("biar pun","biarpun{*biar pun}")
		:gsub("mau pun","maupun{*mau pun}")
		:gsub("meski pun","meskipun{*meski pun}")
		:gsub("abjat","abjad{*abjat}")
		:gsub("aktifitas","aktivitas{*aktifitas}")
		:gsub("antri","antre{*antri}")
		:gsub("apotik","apotek{*apotik}")
		:gsub("atlit","atlet{*atlit}")
		:gsub("cabe","cabai{*cabe}")
		:gsub("pondasi","fondasi{*pondasi}")
		:gsub("frekwensi","frekuensi{*frekwensi}")
		:gsub("gubug","gubuk{*gubug}")
		:gsub("hakekat","hakikat{*hakekat}")
		:gsub("indera","indra{*indera}")
		:gsub("isteri","istri{*isteri}")
		:gsub("jendral","jenderal{*jendral}")
		:gsub("komplit","komplet{*komplit}")
		:gsub("kwalitas","kualitas{*kwalitas}")
		:gsub("kwitansi","kuitansi{*kwitansi}")
		:gsub("lobang","lubang{*lobang}")
		:gsub("milyar","miliar{*milyar}")
		:gsub("nomer","nomor{*}")
		:gsub("faham","paham{*faham}")
		:gsub("fikir","pikir{*fikir}")
		:gsub("praktek","praktik{*praktek}")
		:gsub("tehnik","teknik{*tehnik}")
		:gsub("malpraktik","malapraktik{*malpraktik}")
		:gsub("malfungsi","malafungsi{*malfungsi}")
		:gsub("akte","akta{*akte}")
		:gsub("ketapel","katapel{*ketapel}")
		:gsub("senggama","sanggama{*senggama}")
		:gsub("semedi","semadi{*semedi}")
		:gsub("amandemen","amendemen{*amandemen}")
		:gsub("aritmatika","aritmetika{*aritmatika}")
		:gsub("metoda","metode{*metoda}")
		:gsub("materai","meterai{*materai}")
		:gsub("kalendar","kalender{*kalendar}")
		:gsub("kadaluwarsa","kedaluwarsa{*kadaluwarsa}")
		:gsub("katagori","kategori{*kategori}")
		:gsub("sekular","sekuler{*sekular}")
		:gsub("selular","seluler{*selular}")
		:gsub("sirkular","sirkuler{*sirkular}")
		:gsub("survey","survei{*survey}")
		:gsub("formil","formal{*formil}")
		:gsub("komersil","komersial{*komersil}")
		:gsub("orisinil","orisinal{*orisinil}")
		:gsub("afdol","afdal{*afdol}")
		:gsub("cidera","cedera{*cidera}")
		:gsub("cendikiawan","cendekiawan{*cendikiawan}")
		:gsub("cinderamata","cenderamata{*cinderamata}")
		:gsub("diskotik","diskotek{*diskotik}")
		:gsub("ekstrim","ekstrem{*ekstrim}")
		:gsub("pinalti","penalti{*pinalti}")
		:gsub("piranti","peranti{*piranti}")
		:gsub("teoritis","teoretis{*teoritis}")
		:gsub("cengkeh","cengkih{*cengkeh}")
		:gsub("desertasi","disertasi{*desertasi}")
		:gsub("kaedah","kaidah{*kaedah}")
		:gsub("kempes","kempis{*kempes}")
		:gsub("retsleting","ritsleting{*retsleting}")
		:gsub("amuba","ameba{*amuba}")
		:gsub("punggawa","penggawa{*punggawa}")
		:gsub("surban","serban{*surban}")
		:gsub("kantung","kantong{*kantung}")
		:gsub("pastur","pastor{*pastur}")
		:gsub("supir","sopir{*supir}")
		:gsub("mangkok","mangkuk{*mangkok}")
		:gsub("saos","saus{*saos}")
		:gsub("sop","sup{*sop}")
		:gsub("obrak-abrik","ubrak-abrik{*obrak-abrik}")
		:gsub("kwalitas","kualitas{*kwalitas}")
		:gsub("kwintal","kuintal{*kwintal}")
		:gsub("hirarki","hierarki{*hirarki}")
		:gsub("insyaf","insaf{*insyaf}")
		:gsub("aktifis","aktivis{*aktifis}")
		:gsub("jerembab","jerembap{*jerembab}")
		:gsub("sembab","sembap{*sembab}")
		:gsub("tekat","tekad{*tekat}")
		:gsub("nekad","nekat{*nekad}")
		:gsub("bejad","bejat{*bejad}")
		:gsub("jenius","genius{*jenius}")
		:gsub("obyek","objek{*obyek}")
		:gsub("subyek","subjek{*subyek}")
		:gsub("jamrud","zamrud{*jamrud}")
		:gsub("kripik","keripik{*kripik}")
		:gsub("krupuk","kerupuk{*krupuk}")
		:gsub("ksatria","kesatria{*ksatria}")
		:gsub("sumatra","sumatera{*sumatra}")
		:gsub("trampil","terampil{*trampil}")
		:gsub("samudera","samudra{*samudera}")
		:gsub("terompet","trompet{*terompet}")
		:gsub("nahkoda","nakhoda{*nahkoda}")
		:gsub("tahta","takhta{*tahta}")
		:gsub("tahayul","takhayul{*tahayul}")
		:gsub("kharisma","karisma{*kharisma}")
		:gsub("syaraf","saraf{*syaraf}")
		:gsub("do'a","doa{*do'a}")
		:gsub("jum'at","jumat{*jum'at}")
		:gsub("mu'jizat","mukjizat{*mu'jizat}")
		:gsub("analisa","analisis{*analisa}")
		:gsub("diagnosa","diagnosis{*diagnosa}")
		:gsub("hipotesa","hipotesis{*hipotesa}")
		:gsub("sintesa","sintesis{*sintesa}")
		:gsub("produktifitas","produktivitas{*produktifitas}")
		:gsub("kreatifitas","kreativitas{*kreatifitas}")
		:gsub("efektifitas","efektivitas{*efektifitas}")
		:gsub("sportifitas","sportivitas{*sportifitas}")
		:gsub("selebriti","selebritas{*selebriti}")
		:gsub("validiti","validitas{*validiti}")
		:gsub("didramatisir","didramatisasi{*didramatisir}")
		:gsub("dinetralisir","dinetralisasi{*dinetralisir}")
		:gsub("koordinir","koordinasi{*koordinir}")
		:gsub("terorganisir","terorganisasi{*terorganisir}")
		:gsub("terealisir","terealisasi{*terealisir}")
		:gsub("pungkir","mungkir{*pungkir}")
		:gsub("hantar","antar{*hantar}")
		:gsub("panutan","anutan{*panutan}")
		:gsub("greget","gereget{*greget}")
		:gsub("klenteng","kelenteng{*klenteng}")
		:gsub("skak","sekak{*skak}")
		:gsub("stir","setir{*stir}")
		:gsub("ceret","cerek{*ceret}")
		:gsub("gombrong","gombroh{*gombrong}")
		:gsub("carut-marut","karut-marut{*carut-marut}")
		:gsub("mahzab","mazhab{*mahzab}")
		:gsub("negoisasi","negosiasi{*negoisasi}")
		:gsub("rileks","relaks{*rileks}")
		:gsub("sensorik","sensoris{*sensorik}")
		:gsub("tauge","taoge{*tauge}")
		:gsub("tauladan","teladan{*tauladan}")
		:gsub("taubat","tobat{*taubat}")
		:gsub("rapih","rapi{*rapih}")
		:gsub("terpercik","tepercik{*terpercik}")
		:gsub("berterbangan","beterbangan{*berterbangan}")
		:gsub("terperdaya","teperdaya{*terpedaya}")
		:gsub("hadang","adang{*hadang}")
		:gsub("menghadang","mengadang{*menghadang}")
		:gsub("hujam","hunjam{*hujam}")
		:gsub("menghujam","menghunjam{*menghujam}")
		:gsub("rubah","ubah{*rubah}")
		:gsub("merubah","mengubah{*merubah}")
		:gsub("hulu balang","hulubalang{*hulu balang}")
		:gsub("mana kala","manakala{*mana kala}")
		:gsub("walikota","wali kota{*walikota}")
		:gsub("adzan","azan{*adzan}")
		:gsub("ustadz","ustaz{*ustadz}")
		:gsub("dzikir","zikir{*dzikir}")
		:gsub("shalat","salat{*shalat}")
		:gsub("dzuhur","zuhur{*dzuhur}")
		:gsub("maghrib","magrib{*maghrib}")
		:gsub("ramadhan","ramadan{*ramadhan}")
		:gsub("raka'at","rakaat{*raka'at}")
		:gsub("taqwa","takwa{*taqwa}")
		:gsub("muadzin","muazin{*muadzin}")

		-- Kapital

		:gsub("Sekedar","Sekadar{*sekedar}")
		:gsub("Terimakasih","Terima kasih{*terimakasih}")
		:gsub("Dimana","Di mana{*dimana}")
		:gsub("Terlanjur","Telanjur{*terlanjur}")
		:gsub("Terlantar","Telantar{*terlantar}")
		:gsub("Frustasi","Frustrasi{*frustasi}")
		:gsub("Bis","Bus{*bis}")
		:gsub("Coklat","Cokelat{*cokelat}")
		:gsub("Hembus","Embus{*hembus}")
		:gsub("Goa","Gua{*goa}")
		:gsub("Harafiah","Harfiah{*harafiah}")
		:gsub("Himbau","Imbau{*himbau}")
		:gsub("Jerigen","Jeriken{*jerigen}")
		:gsub("Kaos","Kaus{*kaos}")
		:gsub("Lembab","Lembap{*lembab}")
		:gsub("Centimeter","Sentimeter{*centimeter}")
		:gsub("Seksama","Saksama{*seksama}")
		:gsub("Terong","Terung{*terong}")
		:gsub("Hutang","Utang{*hutang}")
		:gsub("Jaman","Zaman{*jaman}")
		:gsub("Rejeki","Rezeki{*rejeki}")
		:gsub("Silahkan","Silakan{*silahkan}")
		:gsub("Karir","Karier{*karir}")
		:gsub("Himpit","Impit{*himpit}")
		:gsub("Karuan","Keruan{*karuan}")
		:gsub("Darimana","Dari mana{*darimana}")
		:gsub("Dari pada","Daripada{*dari pada}")
		:gsub("Kemana","Ke mana{*kemana}")
		:gsub("Kesana","Ke sana{*}Kesana")
		:gsub("Nampak","Tampak{*nampak}")
		:gsub("Tauco","Taoco{*tauco}")
		:gsub("Nafas","Napas{*nafas}")
		:gsub("Personil","Personel{*personil}")
		:gsub("Resiko","Risiko{*resiko}")
		:gsub("Anugrah","Anugerah{*anugrah}")
		:gsub("Detil","Detail{*detil}")
		:gsub("Mempedulikan","Memedulikan{*mempedulikan}")
		:gsub("Memperhatikan","Memerhatikan{*memperhatikan}")
		:gsub("Mempengaruhi","Memengaruhi{*mempengaruhi}")
		:gsub("Mengkupas","Mengupas{*mengkupas}")
		:gsub("Mengkorupsi","Mengorupsi{*mengkorupsi}")
		:gsub("Mempesona","Memesona{*mempesona}")
		:gsub("Hapal","Hafal{*hapal}")
		:gsub("Ijin","Izin{*ijin}")
		:gsub("Sumringah","Semringah{*sumringah}")
		:gsub("Sistim","Sistem{*sistim}")
		:gsub("Hentak","Entak{*hentak}")
		:gsub("Brengsek","Berengsek{*brengsek}")
		:gsub("Hisap","Isap{*hisap}")
		:gsub("Handal","Andal{*handal}")
		:gsub("Ada pun","Adapun{*ada pun}")
		:gsub("Andai pun","Andaipun{*andai pun}")
		:gsub("Atau pun","Ataupun{*atau pun}")
		:gsub("Bagaimana pun","Bagaimanapun{*bagaimana pun}")
		:gsub("Kendati pun","Kendatipun{*kendati pun}")
		:gsub("Sungguh pun","Sungguhpun{*sungguh pun}")
		:gsub("Sungguh pun","Sungguhpun{*sungguh pun}")
		:gsub("Sekali pun","Sekalipun{*sekali pun}")
		:gsub("Kalau pun","Kalaupun{*kalau pun}")
		:gsub("Walau pun","Walaupun{*walau pun}")
		:gsub("Biar pun","Biarpun{*biar pun}")
		:gsub("Mau pun","Maupun{*mau pun}")
		:gsub("Meski pun","Meskipun{*meski pun}")
		:gsub("Abjat","Abjad{*abjat}")
		:gsub("Aktifitas","Aktivitas{*aktifitas}")
		:gsub("Antri","Antre{*antri}")
		:gsub("Apotik","Apotek{*apotik}")
		:gsub("Atlit","Atlet{*atlit}")
		:gsub("Cabe","Cabai{*cabe}")
		:gsub("Pondasi","Fondasi{*pondasi}")
		:gsub("Frekwensi","Frekuensi{*frekwensi}")
		:gsub("Gubug","Gubuk{*gubug}")
		:gsub("Hakekat","Hakikat{*hakekat}")
		:gsub("Indera","Indra{*indera}")
		:gsub("Isteri","Istri{*isteri}")
		:gsub("Jendral","Jenderal{*jendral}")
		:gsub("Komplit","Komplet{*komplit}")
		:gsub("Kwalitas","Kualitas{*kwalitas}")
		:gsub("Kwitansi","Kuitansi{*kwitansi}")
		:gsub("Lobang","Lubang{*lobang}")
		:gsub("Milyar","Miliar{*milyar}")
		:gsub("Nomer","Nomor{*}")
		:gsub("Faham","Paham{*faham}")
		:gsub("Fikir","Pikir{*fikir}")
		:gsub("Praktek","Praktik{*praktek}")
		:gsub("Tehnik","Teknik{*tehnik}")
		:gsub("Malpraktik","Malapraktik{*malpraktik}")
		:gsub("Malfungsi","Malafungsi{*malfungsi}")
		:gsub("Akte","Akta{*akte}")
		:gsub("Ketapel","Katapel{*ketapel}")
		:gsub("Senggama","Sanggama{*senggama}")
		:gsub("Semedi","Semadi{*semedi}")
		:gsub("Amandemen","Amendemen{*amandemen}")
		:gsub("Aritmatika","Aritmetika{*aritmatika}")
		:gsub("Metoda","Metode{*metoda}")
		:gsub("Materai","Meterai{*materai}")
		:gsub("Kalendar","Kalender{*kalendar}")
		:gsub("Kadaluwarsa","Kedaluwarsa{*kadaluwarsa}")
		:gsub("Katagori","Kategori{*kategori}")
		:gsub("Sekular","Sekuler{*sekular}")
		:gsub("Selular","Seluler{*selular}")
		:gsub("Sirkular","Sirkuler{*sirkular}")
		:gsub("Survey","Survei{*survey}")
		:gsub("Formil","Formal{*formil}")
		:gsub("Komersil","Komersial{*komersil}")
		:gsub("Orisinil","Orisinal{*orisinil}")
		:gsub("Afdol","Afdal{*afdol}")
		:gsub("Cidera","Cedera{*cidera}")
		:gsub("Cendikiawan","Cendekiawan{*cendikiawan}")
		:gsub("Cinderamata","Cenderamata{*cinderamata}")
		:gsub("Diskotik","Diskotek{*diskotik}")
		:gsub("Ekstrim","Ekstrem{*ekstrim}")
		:gsub("Pinalti","Penalti{*pinalti}")
		:gsub("Piranti","Peranti{*piranti}")
		:gsub("Teoritis","Teoretis{*teoritis}")
		:gsub("Cengkeh","Cengkih{*cengkeh}")
		:gsub("Desertasi","Disertasi{*desertasi}")
		:gsub("Kaedah","Kaidah{*kaedah}")
		:gsub("Kempes","Kempis{*kempes}")
		:gsub("Retsleting","Ritsleting{*retsleting}")
		:gsub("Amuba","Ameba{*amuba}")
		:gsub("Punggawa","Penggawa{*punggawa}")
		:gsub("Surban","Serban{*surban}")
		:gsub("Kantung","Kantong{*kantung}")
		:gsub("Pastur","Pastor{*pastur}")
		:gsub("Supir","Sopir{*supir}")
		:gsub("Mangkok","Mangkuk{*mangkok}")
		:gsub("Saos","Saus{*saos}")
		:gsub("Sop","Sup{*sop}")
		:gsub("Obrak-abrik","Ubrak-abrik{*obrak-abrik}")
		:gsub("Kwalitas","Kualitas{*kwalitas}")
		:gsub("Kwintal","Kuintal{*kwintal}")
		:gsub("Hirarki","Hierarki{*hirarki}")
		:gsub("Insyaf","Insaf{*insyaf}")
		:gsub("Aktifis","Aktivis{*aktifis}")
		:gsub("Jerembab","Jerembap{*jerembab}")
		:gsub("Sembab","Sembap{*sembab}")
		:gsub("Tekat","Tekad{*tekat}")
		:gsub("Nekad","Nekat{*nekad}")
		:gsub("Bejad","Bejat{*bejad}")
		:gsub("Jenius","Genius{*jenius}")
		:gsub("Obyek","Objek{*obyek}")
		:gsub("Subyek","Subjek{*subyek}")
		:gsub("Jamrud","Zamrud{*jamrud}")
		:gsub("Kripik","Keripik{*kripik}")
		:gsub("Krupuk","Kerupuk{*krupuk}")
		:gsub("Ksatria","Kesatria{*ksatria}")
		:gsub("Sumatra","Sumatera{*sumatra}")
		:gsub("Trampil","Terampil{*trampil}")
		:gsub("Samudera","Samudra{*samudera}")
		:gsub("Terompet","Trompet{*terompet}")
		:gsub("Nahkoda","Nakhoda{*nahkoda}")
		:gsub("Tahta","Takhta{*tahta}")
		:gsub("Tahayul","Takhayul{*tahayul}")
		:gsub("Kharisma","Karisma{*kharisma}")
		:gsub("Syaraf","Saraf{*syaraf}")
		:gsub("Do'a","Doa{*do'a}")
		:gsub("Jum'at","Jumat{*jum'at}")
		:gsub("Mu'jizat","Mukjizat{*mu'jizat}")
		:gsub("Analisa","Analisis{*analisa}")
		:gsub("Diagnosa","Diagnosis{*diagnosa}")
		:gsub("Hipotesa","Hipotesis{*hipotesa}")
		:gsub("Sintesa","Sintesis{*sintesa}")
		:gsub("Produktifitas","Produktivitas{*produktifitas}")
		:gsub("Kreatifitas","Kreativitas{*kreatifitas}")
		:gsub("Efektifitas","Efektivitas{*efektifitas}")
		:gsub("Sportifitas","Sportivitas{*sportifitas}")
		:gsub("Selebriti","Selebritas{*selebriti}")
		:gsub("Validiti","Validitas{*validiti}")
		:gsub("Didramatisir","Didramatisasi{*didramatisir}")
		:gsub("Dinetralisir","Dinetralisasi{*dinetralisir}")
		:gsub("Koordinir","Koordinasi{*koordinir}")
		:gsub("Terorganisir","Terorganisasi{*terorganisir}")
		:gsub("Terealisir","Terealisasi{*terealisir}")
		:gsub("Pungkir","Mungkir{*pungkir}")
		:gsub("Hantar","Antar{*hantar}")
		:gsub("Panutan","Anutan{*panutan}")
		:gsub("Greget","Gereget{*greget}")
		:gsub("Klenteng","Kelenteng{*klenteng}")
		:gsub("Skak","Sekak{*skak}")
		:gsub("Stir","Setir{*stir}")
		:gsub("Ceret","Cerek{*ceret}")
		:gsub("Gombrong","Gombroh{*gombrong}")
		:gsub("Carut-marut","Karut-marut{*carut-marut}")
		:gsub("Mahzab","Mazhab{*mahzab}")
		:gsub("Negoisasi","Negosiasi{*negoisasi}")
		:gsub("Rileks","Relaks{*rileks}")
		:gsub("Sensorik","Sensoris{*sensorik}")
		:gsub("Tauge","Taoge{*tauge}")
		:gsub("Tauladan","Teladan{*tauladan}")
		:gsub("Taubat","Tobat{*taubat}")
		:gsub("Rapih","Rapi{*rapih}")
		:gsub("Terpercik","Tepercik{*terpercik}")
		:gsub("Berterbangan","Beterbangan{*berterbangan}")
		:gsub("Terperdaya","Teperdaya{*terpedaya}")
		:gsub("Hadang","Adang{*hadang}")
		:gsub("Menghadang","Mengadang{*menghadang}")
		:gsub("Hujam","Hunjam{*hujam}")
		:gsub("Menghujam","Menghunjam{*menghujam}")
		:gsub("Rubah","Ubah{*rubah}")
		:gsub("Merubah","Mengubah{*merubah}")
		:gsub("Hulu balang","Hulubalang{*hulu balang}")
		:gsub("Mana kala","Manakala{*mana kala}")
		:gsub("Walikota","Wali kota{*walikota}")
		:gsub("Adzan","Azan{*adzan}")
		:gsub("Ustadz","Ustaz{*ustadz}")
		:gsub("Dzikir","Zikir{*dzikir}")
		:gsub("Shalat","Salat{*shalat}")
		:gsub("Dzuhur","Zuhur{*dzuhur}")
		:gsub("Maghrib","Magrib{*maghrib}")
		:gsub("Ramadhan","Ramadan{*ramadhan}")
		:gsub("Raka'at","Rakaat{*raka'at}")
		:gsub("Taqwa","Takwa{*taqwa}")
		:gsub("Muadzin","Muazin{*muadzin}")
		--kebiasan si fadli bangsat
		:gsub(", kan?",", 'kan")
		--------------------------
		if text:match("{%*[^}]-}") then line.actor="Tolong lebih teliti lagi, Mas!" end

	    line.text=text
            subs[i]=line
	end
    end

end

--------------------------------------------------------------------

function main(subs,sel,act)
ADD=aegisub.dialog.display
GUI=
{
    {x=0,y=0,width=1,height=1,class="label",label="KBBI 5 Koreksi Otomatis"},
	{x=13,y=0,width=1,height=1,class="label",label="Versi 1.0.2"},
}
P,res=ADD(GUI,
{"Terapkan Pada Seluruh Line","Terapkan Pada Line Yang Disorot"})
if P=="Terapkan Pada Seluruh Line" then kbbi(subs) end
if P=="Terapkan Pada Line Yang Disorot" then kbbi_seleksi(subs, sel) end
aegisub.set_undo_point(script_name)
    return sel,act
end

if haveDepCtrl then depRec:registerMacro(main) else aegisub.register_macro(script_name,script_description,main) end

